module.exports={
    development:{
        "database":"salesmanager-product",
        "host":"product-db",
        "username":"postgres",
        "password":"postgres",
        "dialect":"postgres"
    },
    test:{
        "database":"salesmanager-product",
        "host":"192.168.99.100",
        "username":"postgres",
        "password":"postgres",
        "dialect":"postgres"
    },
    production:{
        "database":"salesmanager-product",
        "host":"product-db",
        "username":"postgres",
        "password":"postgres",
        "dialect":"postgres"
    },
    
}